services:
  - type: web
    name: newsgraph-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GNEWS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE_MINUTES
        value: "720"
    plan: free
